### ISSUE TITLE
Pickle issue using Dramatiq

### ISSUE THREAD

**Issue by BboyKeen** [jcass77/django-apscheduler#142]
Hi there,

First of all, thanks for your implementation :)

I was trying to use this package with Dramatiq but I face a pickle issue even with the simple example from Dramatiq.
When I launch my scheduler, I encounter the following issue : `pickle.PicklingError: Can't pickle <function print_current_date at 0x7f0efd15d040>: it's not the same object as __main__.print_current_date`

Here is the example code I use : 

```python
import logging
import sys
logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)
import datetime
import dramatiq
import os

import django
os.environ['DJANGO_SETTINGS_MODULE'] = 'settings'

django.setup()


from apscheduler.schedulers.blocking import BlockingScheduler
from apscheduler.triggers.cron import CronTrigger
from django_apscheduler.jobstores import DjangoJobStore
from django_apscheduler.models import DjangoJobExecution

logger = logging.getLogger(__name__)

@dramatiq.actor
def print_current_date():
    print(datetime.now())



if __name__ == "__main__":
    scheduler = BlockingScheduler(timezone='UTC')
    scheduler.add_jobstore(DjangoJobStore(), "default")

    scheduler.add_job(
        print_current_date.send,
        trigger=CronTrigger(second="*/10"),  # Every 10 seconds
        id="my_job",  # The `id` assigned to each job MUST be unique
        max_instances=1,
        replace_existing=True,
    )

    try:
        logger.info("Starting scheduler...")
        scheduler.start()
    except KeyboardInterrupt:
        logger.info("Stopping scheduler...")
        scheduler.shutdown()
        logger.info("Scheduler shut down successfully!")
```

Any idea what could cause the issue ?

Thanks for your help !

Edit : My current workaround is to use which works fine. Maybe it could be added in the project documentation

```python
def run_dramatiq_task_print_current_date():
    print_current_date.send()

if __name__ == "__main__":
    scheduler = BlockingScheduler(timezone='UTC')
    scheduler.add_jobstore(DjangoJobStore(), "default")

    scheduler.add_job(
        run_dramatiq_task_print_current_date,
        trigger=CronTrigger(second="*/10"),  # Every 10 seconds
        id="my_job",  # The `id` assigned to each job MUST be unique
        max_instances=1,
        replace_existing=True,
    )
```

**Comment by jcass77** [comment]
Thanks for drawing attention to this issue - I think the problem is that Dramatiq's `Actor.send` method actually returns a reference to `Actor.send_with_options`.

According to the [Python documentation](https://docs.python.org/3/library/pickle.html#what-can-be-pickled-and-unpickled), it doesn't look like instance methods can be pickled in that way. Instead, you need to use:

> functions defined at the top level of a module (using def, not lambda)

...which is the approach outlined in your workaround above (I use the same approach in my own projects as well by the way). 

The example that you cited when logging this issue comes from the Dramatiq [project documentation](https://dramatiq.io/cookbook.html?highlight=apscheduler#scheduling-messages). It might be best to submit a pull request to that project for fixing the example in their project docs.
