### ISSUE TITLE
it cannot specify function name and args when add job  by django admin page 

### ISSUE THREAD

**Issue by ydf0509** [jcass77/django-apscheduler#149]
http://127.0.0.1:8000/admin/django_apscheduler/djangojob/add/

in this url page，user cannot specify which func and params to run this job，is there any way user can specify job func and args by django admin page when add job 

![image](https://user-images.githubusercontent.com/26890690/123944324-9b2ff080-d9cf-11eb-882a-b4f6a4d4bb66.png)

**Comment by ydf0509** [comment]
i think the frame can force user import the fun in the  apschedluer instnce script，so that user can select which fun to run the job by admin page.

django-celery-beat can add job by admin page

**Comment by ydf0509** [comment]
i think the frame should can specify function name ,args, and trigger way by admin page.i need this

**Comment by jcass77** [comment]
APScheduler jobs have to be created and scheduled in your Python code.

It is not possible to create new jobs via the standard Django admin interface since:

1. you need to start an APScheduler scheduler as part of a dedicated management command; and
2. once your scheduler is running, there is currently no way to notify APScheduler that a new job is available in the database for it to process.

Please refer to the README for details.

**Comment by ydf0509** [comment]
i think user can define a map like this,    {"funca":funca,"add":add}

and user can select funca /add, and specify args and trigger way in the admin page

**Comment by ydf0509** [comment]
why django-celery-beat can speciy job task args and trigger by admin page

**Comment by jcass77** [comment]
> why django-celery-beat can speciy job task args and trigger by admin page

...because it uses Celery, not APScheduler. These two background processing libraries have different architectures with different limitations.
