### ISSUE TITLE
 Would it be possible to set a Sleep to allow for API limits?

### ISSUE THREAD

**Issue by igalci** [jcass77/django-apscheduler#153]
I was thinking of using Apscheduler to schedule API calls, but I would need to have my tasks sleep a certain time for every different API I am accessing.

I think a solution would be to limit # of workers to 1, and then have the tasks sleep after they are finished. However, this will not account for different APIs which can be accessed simultaneously without a problem.

I thought maybe Apscheduler has a more sophisticated approach to this case?

**Comment by jcass77** [comment]
Not sure I understand why just scheduling calls to the API endpoints individually won’t work.

If there are dependencies **between** API endpoints then wrapping those calls into a single scheduled job, that manages the order of the calls and waits for responses, should also be fine.

django-apscheduler is just a job store for APScheduler, and does not provide any scheduling features itself.

**Comment by igalci** [comment]
I am using [YFinance](https://github.com/ranaroussi/yfinance) and similar APIs to scrape the web. I need to get data for each of ~2000 stock market tickers every week or so. So if I run my job every 10 minutes, I should be good. I don't want to schedule everyone of the 2000 jobs individually with a specific time at which it will run. It would be easier to simply have a queue with a sleep in between.

Additionally, I am scraping for the 2000 tickers using [Investpy](https://github.com/alvarobartt/investpy) which could run alongside my first job.

So I was thinking if APScheduler would be appropriate for this. Could I set up 2 separate queues using APScheduler and assign 1 worker to each so the sleep times in between are respected?

**Comment by jcass77** [comment]
You probably don't need to assign workers explicitly. You should be able to just schedule two separate jobs (one using YFinance, and one using Investpy) that run every 10 minutes and fetches data for the next stock ticker.

The above does not sound terribly efficient though and, depending on the rate limits imposed by the API's that provide the data, it might make more sense to introduce a basic level of concurrency that would allow you to make at least some of the API calls in parallel.

Closing since a feature like this is beyond the scope of django-apscheduler.
