### ISSUE TITLE
Add @util.close_old_connections in the _get_jobs(self, **filters) funtion for the DB connection

### ISSUE THREAD

**Issue by Tony20221101** [jcass77/django-apscheduler#176]
**DB：Mysql**

**Only add the @util.close_old_connections in the event does not help me**
It will raise the ERROR: 2013, 'Lost connection to MySQL server during query'

**To Reproduce**
1. Add @util.close_old_connections only in the event
2. Set the interval = 1 hour between 9:00am to 12:00am
3. The event will success in the first time at 9:00am
4. The event will fail in the second time at 10:00am, and raise the ERROR: 2013, 'Lost connection to MySQL server during query'
5. This ERROR will also happend in the later executions

**Idea**
Add @util.close_old_connections in the _get_jobs(self, **filters) funtion works for me

I rewrite the class DjangoJobStore() by add the @util.close_old_connections in the _get_jobs(self, **filters) funtion. 
It success.

**Screenshots**
![image](https://user-images.githubusercontent.com/117441493/199943136-bbc32590-56d4-48f3-8f68-86a572d1b8ab.png)

**Comment by jcass77** [comment]
https://github.com/jcass77/django-apscheduler/blob/62e38372b30fad72f04086f5f0d66a07e309d83f/django_apscheduler/util.py#L78-L82 provides an explanation of why we are not currently following that approach.

We can revisit if the Django implementation details have since changed and somebody can provide relevant references and examples though.
